#Colorize ls output
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

export PS1='\w\$ '  # Note ' quotes rather than " quotes
#Alias definitions are imported from ~/.bash_aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

function cd () {
  local -ri n=${#*};
  if [ $n -eq 0 -o -d "${!n}" -o "${!n}" == "-" ]; then
    builtin cd "$@";
  else
    local e="s:\.\.\.:../..:g";
    builtin cd "${@:1:$n-1}" $(sed -e$e -e$e -e$e <<< "${!n}");
  fi
}
